displayName=Sailing Reorderer
author=marknewan
description=Reorder the sailing side panel facilities
tags=sailing,side,panel,reorder,rearrange,reposition,facilities,boat
version=1.1.2
plugins=com.sailingreorderer.SailingReordererPlugin
build=standard