package com.boathider;

import java.util.Set;
import lombok.experimental.UtilityClass;
import net.runelite.api.gameval.ObjectID;

@UtilityClass
class BoatID
{
	final Set<Integer> WORLD_ENTITY_TYPE_BOAT = Set.of(1, 2, 3);

	final Set<Integer> SAIL_IDS = Set.of(
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_WOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_WOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_WOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_OAK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_OAK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_OAK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_TEAK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_TEAK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_TEAK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_MAHOGANY,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_MAHOGANY,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_MAHOGANY,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_CAMPHOR,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_CAMPHOR,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_CAMPHOR,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_IRONWOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_IRONWOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_IRONWOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_ROSEWOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_ROSEWOOD,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_ROSEWOOD
	);

	final Set<Integer> HULL_IDS = Set.of(
		ObjectID.SAILING_BOAT_HULL_KANDARIN_1X3_WOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_2X5_WOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_3X8_WOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_1X3_OAK,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_2X5_OAK,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_3X8_OAK,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_1X3_TEAK,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_2X5_TEAK,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_3X8_TEAK,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_1X3_MAHOGANY,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_2X5_MAHOGANY,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_3X8_MAHOGANY,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_1X3_CAMPHOR,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_2X5_CAMPHOR,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_3X8_CAMPHOR,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_1X3_IRONWOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_2X5_IRONWOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_3X8_IRONWOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_1X3_ROSEWOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_2X5_ROSEWOOD,
		ObjectID.SAILING_BOAT_HULL_KANDARIN_3X8_ROSEWOOD
	);

	final Set<Integer> HELM_IDS = Set.of(
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_WOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_WOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_WOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_WOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_WOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_WOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_WOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_WOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_WOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_OAK,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_OAK_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_OAK_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_OAK,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_OAK_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_OAK_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_OAK,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_OAK_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_OAK_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_TEAK,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_TEAK_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_TEAK_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_TEAK,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_TEAK_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_TEAK_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_TEAK,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_TEAK_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_TEAK_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_MAHOGANY,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_MAHOGANY_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_MAHOGANY_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_MAHOGANY,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_MAHOGANY_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_MAHOGANY_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_MAHOGANY,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_MAHOGANY_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_MAHOGANY_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_CAMPHOR,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_CAMPHOR_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_CAMPHOR_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_CAMPHOR,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_CAMPHOR_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_CAMPHOR_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_CAMPHOR,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_CAMPHOR_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_CAMPHOR_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_IRONWOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_IRONWOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_IRONWOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_IRONWOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_IRONWOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_IRONWOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_IRONWOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_IRONWOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_IRONWOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_ROSEWOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_ROSEWOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_ROSEWOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_ROSEWOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_ROSEWOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_ROSEWOOD_IDLE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_ROSEWOOD,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_ROSEWOOD_IN_USE,
		ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_ROSEWOOD_IDLE
	);

	final Set<Integer> KEEL_IDS = Set.of(
		ObjectID.SAILING_KEEL_KANDARIN_2X5_BRONZE,
		ObjectID.SAILING_KEEL_KANDARIN_3X8_BRONZE,
		ObjectID.SAILING_KEEL_KANDARIN_2X5_IRON,
		ObjectID.SAILING_KEEL_KANDARIN_3X8_IRON,
		ObjectID.SAILING_KEEL_KANDARIN_2X5_STEEL,
		ObjectID.SAILING_KEEL_KANDARIN_3X8_STEEL,
		ObjectID.SAILING_KEEL_KANDARIN_2X5_MITHRIL,
		ObjectID.SAILING_KEEL_KANDARIN_3X8_MITHRIL,
		ObjectID.SAILING_KEEL_KANDARIN_2X5_ADAMANT,
		ObjectID.SAILING_KEEL_KANDARIN_3X8_ADAMANT,
		ObjectID.SAILING_KEEL_KANDARIN_2X5_RUNE,
		ObjectID.SAILING_KEEL_KANDARIN_3X8_RUNE,
		ObjectID.SAILING_KEEL_KANDARIN_2X5_DRAGON,
		ObjectID.SAILING_KEEL_KANDARIN_3X8_DRAGON
	);

	final Set<Integer> WIND_CATCHER_IDS = Set.of(
		ObjectID.SAILING_WIND_CATCHER_ACTIVATED,
		ObjectID.SAILING_WIND_CATCHER_DEACTIVATED,
		ObjectID.SAILING_GALE_CATCHER_ACTIVATED,
		ObjectID.SAILING_GALE_CATCHER_DEACTIVATED
	);

	final Set<Integer> CRYSTAL_EXTRACTOR_IDS = Set.of(
		ObjectID.SAILING_CRYSTAL_EXTRACTOR_ACTIVATED,
		ObjectID.SAILING_CRYSTAL_EXTRACTOR_DEACTIVATED
	);

	final Set<Integer> SALVAGING_STATION_IDS = Set.of(
		ObjectID.SAILING_SALVAGING_STATION_2X5A,
		ObjectID.SAILING_SALVAGING_STATION_2X5B,
		ObjectID.SAILING_SALVAGING_STATION_3X8
	);

	final Set<Integer> CARGO_HOLD_IDS = Set.of(
		ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_RAFT,
		ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_RAFT_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_2X5,
		ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_2X5_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_LARGE,
		ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_LARGE_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_RAFT,
		ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_RAFT_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_2X5,
		ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_2X5_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_LARGE,
		ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_LARGE_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_RAFT,
		ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_RAFT_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_2X5,
		ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_2X5_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_LARGE,
		ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_LARGE_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_RAFT,
		ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_RAFT_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_2X5,
		ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_2X5_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_LARGE,
		ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_LARGE_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_RAFT,
		ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_RAFT_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_2X5,
		ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_2X5_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_LARGE,
		ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_LARGE_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_RAFT,
		ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_RAFT_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_2X5,
		ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_2X5_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_LARGE,
		ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_LARGE_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_RAFT,
		ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_RAFT_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_2X5,
		ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_2X5_OPEN,
		ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_LARGE,
		ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_LARGE_OPEN
	);

	final Set<Integer> TELEPORTATION_FOCUS_IDS = Set.of(
		ObjectID.SAILING_TELEPORTATION_FOCUS,
		ObjectID.SAILING_TELEPORTATION_FOCUS_GREATER
	);

	final Set<Integer> TRIM_IDS = Set.of(
		ObjectID.SAILING_BOAT_SKIFF_TRIM_WOODEN,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_OAK,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_TEAK,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_MAHOGANY,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_CAMPHOR,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_IRONWOOD,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_ROSEWOOD,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_BARRACUDA,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_SHARK,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_INKY,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_ANGLERS,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_SALVORS,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_ARMADYLEAN,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_ZAMORAKIAN,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_GUTHIXIAN,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_SARADOMINIST,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_MERCHANTS,
		ObjectID.SAILING_BOAT_SKIFF_TRIM_SANDY,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_WOODEN,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_OAK,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_TEAK,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_MAHOGANY,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_CAMPHOR,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_IRONWOOD,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_ROSEWOOD,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_BARRACUDA,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_SHARK,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_INKY,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_ANGLERS,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_SALVORS,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_ARMADYLEAN,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_ZAMORAKIAN,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_GUTHIXIAN,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_SARADOMINIST,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_MERCHANTS,
		ObjectID.SAILING_BOAT_SLOOP_TRIM_SANDY
	);

	final Set<Integer> SALVAGING_HOOK_IDS = Set.of(
		ObjectID.SALVAGING_HOOK_RAFT_BRONZE,
		ObjectID.SALVAGING_HOOK_BRONZE,
		ObjectID.SALVAGING_HOOK_LARGE_BRONZE,
		ObjectID.SALVAGING_HOOK_LARGE_BRONZE_B,
		ObjectID.SALVAGING_HOOK_RAFT_IRON,
		ObjectID.SALVAGING_HOOK_IRON,
		ObjectID.SALVAGING_HOOK_LARGE_IRON,
		ObjectID.SALVAGING_HOOK_LARGE_IRON_B,
		ObjectID.SALVAGING_HOOK_RAFT_STEEL,
		ObjectID.SALVAGING_HOOK_STEEL,
		ObjectID.SALVAGING_HOOK_LARGE_STEEL,
		ObjectID.SALVAGING_HOOK_LARGE_STEEL_B,
		ObjectID.SALVAGING_HOOK_RAFT_MITHRIL,
		ObjectID.SALVAGING_HOOK_MITHRIL,
		ObjectID.SALVAGING_HOOK_LARGE_MITHRIL,
		ObjectID.SALVAGING_HOOK_LARGE_MITHRIL_B,
		ObjectID.SALVAGING_HOOK_RAFT_ADAMANT,
		ObjectID.SALVAGING_HOOK_ADAMANT,
		ObjectID.SALVAGING_HOOK_LARGE_ADAMANT,
		ObjectID.SALVAGING_HOOK_LARGE_ADAMANT_B,
		ObjectID.SALVAGING_HOOK_RAFT_RUNE,
		ObjectID.SALVAGING_HOOK_RUNE,
		ObjectID.SALVAGING_HOOK_LARGE_RUNE,
		ObjectID.SALVAGING_HOOK_LARGE_RUNE_B,
		ObjectID.SALVAGING_HOOK_RAFT_DRAGON,
		ObjectID.SALVAGING_HOOK_DRAGON,
		ObjectID.SALVAGING_HOOK_LARGE_DRAGON,
		ObjectID.SALVAGING_HOOK_LARGE_DRAGON_B
	);

	final Set<Integer> CANNON_IDS = Set.of(
		ObjectID.SAILING_BRONZE_CANNON,
		ObjectID.SAILING_IRON_CANNON,
		ObjectID.SAILING_STEEL_CANNON,
		ObjectID.SAILING_MITHRIL_CANNON,
		ObjectID.SAILING_ADAMANT_CANNON,
		ObjectID.SAILING_RUNE_CANNON,
		ObjectID.SAILING_DRAGON_CANNON,
		ObjectID.SAILING_GOLD_CANNON
	);

	final Set<Integer> INOCULATION_STATION_IDS = Set.of(
		ObjectID.SAILING_FACILITY_2X5_INOCULATION_STATION,
		ObjectID.SAILING_FACILITY_2X5_INOCULATION_STATION_NOOP,
		ObjectID.SAILING_FACILITY_3X8_INOCULATION_STATION
	);

	final Set<Integer> ETERNAL_BRAZIER_IDS = Set.of(
		ObjectID.SAILING_BOAT_1X3_ETERNAL_BRAZIER,
		ObjectID.SAILING_BOAT_SKIFF_ETERNAL_BRAZIER,
		ObjectID.SAILING_BOAT_SLOOP_ETERNAL_BRAZIER,
		ObjectID.SAILING_BOAT_ETERNAL_BRAZIER_UI
	);

	final Set<Integer> FLAG_IDS = Set.of(
		ObjectID.SAILING_BOAT_1X3_FLAG_TEMPOR_TANTRUM,
		ObjectID.SAILING_BOAT_1X3_FLAG_JUBBLY_JIVE,
		ObjectID.SAILING_BOAT_1X3_FLAG_GWENITH_GLIDE,
		ObjectID.SAILING_BOAT_SKIFF_FLAG_TEMPOR_TANTRUM,
		ObjectID.SAILING_BOAT_SKIFF_FLAG_JUBBLY_JIVE,
		ObjectID.SAILING_BOAT_SKIFF_FLAG_GWENITH_GLIDE,
		ObjectID.SAILING_BOAT_SLOOP_FLAG_TEMPOR_TANTRUM,
		ObjectID.SAILING_BOAT_SLOOP_FLAG_JUBBLY_JIVE,
		ObjectID.SAILING_BOAT_SLOOP_FLAG_GWENITH_GLIDE
	);

	final Set<Integer> KEG_IDS = Set.of(
		ObjectID.SAILING_KEG_EMPTY,
		ObjectID.SAILING_KEG_GROG,
		ObjectID.SAILING_KEG_CIDER,
		ObjectID.SAILING_KEG_WHIRLPOOL_SURPRISE,
		ObjectID.SAILING_KEG_KRAKEN_INK_STOUT,
		ObjectID.SAILING_KEG_PERILDANCE_BITTER,
		ObjectID.SAILING_KEG_TRAWLERS_TRUST,
		ObjectID.SAILING_KEG_HORIZONS_LURE
	);

	final Set<Integer> TRAWLING_NET_IDS = Set.of(
		ObjectID.SAILING_ROPE_TRAWLING_NET,
		ObjectID.SAILING_LINEN_TRAWLING_NET,
		ObjectID.SAILING_HEMP_TRAWLING_NET,
		ObjectID.SAILING_COTTON_TRAWLING_NET,
		ObjectID.SAILING_ROPE_TRAWLING_NET_3X8_STARBOARD,
		ObjectID.SAILING_LINEN_TRAWLING_NET_3X8_STARBOARD,
		ObjectID.SAILING_HEMP_TRAWLING_NET_3X8_STARBOARD,
		ObjectID.SAILING_COTTON_TRAWLING_NET_3X8_STARBOARD,
		ObjectID.SAILING_ROPE_TRAWLING_NET_3X8_PORT,
		ObjectID.SAILING_LINEN_TRAWLING_NET_3X8_PORT,
		ObjectID.SAILING_HEMP_TRAWLING_NET_3X8_PORT,
		ObjectID.SAILING_COTTON_TRAWLING_NET_3X8_PORT
	);

	final Set<Integer> CHUM_STATION_IDS = Set.of(
		ObjectID.CHUM_STATION_2X5A,
		ObjectID.CHUM_STATION_2X5B,
		ObjectID.CHUM_STATION_3X8A,
		ObjectID.CHUM_STATION_3X8B,
		ObjectID.CHUM_STATION_ADVANCED_2X5A,
		ObjectID.CHUM_STATION_ADVANCED_2X5B,
		ObjectID.CHUM_STATION_ADVANCED_3X8A,
		ObjectID.CHUM_STATION_ADVANCED_3X8B,
		ObjectID.CHUM_SPREADER_2X5A,
		ObjectID.CHUM_SPREADER_2X5B,
		ObjectID.CHUM_SPREADER_3X8A,
		ObjectID.CHUM_SPREADER_3X8B
	);

	final Set<Integer> FATHOM_STONE_PEARL_IDS = Set.of(
		ObjectID.SAILING_FATHOM_STONE,
		ObjectID.SAILING_FATHOM_PEARL
	);

	final Set<Integer> ANCHOR_IDS = Set.of(
		ObjectID.SAILING_ANCHOR_RAISED_2X5,
		ObjectID.SAILING_ANCHOR_LOWERED_2X5,
		ObjectID.SAILING_ANCHOR_RAISED_3X8,
		ObjectID.SAILING_ANCHOR_LOWERED_3X8
	);
}
